$axure.loadCurrentPage({
  "url":"注册.html",
  "generationDate":new Date(1431620934535.52),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"4ab0d9861377444288b0ea8a188b2f44",
    "type":"Axure:Page",
    "name":"注册",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"9a06184d26c54ee582ad2ba8c660265f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "size":{
              "width":467,
              "height":830},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d2488b846ba4cb09e901e32eece94de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":467,
                  "height":830},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u1023.png"}},
{
          "id":"3de3bb8115224281b957f06cd9717bbb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF797979},
            "location":{
              "x":-1,
              "y":27},
            "size":{
              "width":469,
              "height":69},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca78d9e4984f4124952d04d573933b7a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF797979},
                "location":{
                  "x":-1,
                  "y":27},
                "size":{
                  "width":469,
                  "height":69},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u2.png"}},
{
          "id":"23e921cbe9714f358e52add9395e50b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF434343},
            "location":{
              "x":-1,
              "y":-3},
            "size":{
              "width":469,
              "height":32},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"438b75b1691c4d8f8f6119953b54dbe9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF434343},
                "location":{
                  "x":-1,
                  "y":-3},
                "size":{
                  "width":469,
                  "height":32},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u4.png"}},
{
          "id":"5a39ed809c424d629545ff67f16aa634",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":19,
              "y":45},
            "size":{
              "width":32,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89632e324f4f46c7bd6d80eb22c2d59c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":19,
                  "y":45},
                "size":{
                  "width":32,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登录",
                      "target":{
                        "targetType":"page",
                        "url":"登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页/u1213.png"}},
{
          "id":"f1efea38a6bd42e1a23790ecf521d90f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":0,
              "y":130},
            "size":{
              "width":468,
              "height":230},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42d4bf1697974e9da2ddefd23937e253",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":0,
                  "y":130},
                "size":{
                  "width":468,
                  "height":230},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u8.png"}},
{
          "id":"3758d401c39d47699c588aa9171428a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC,
              "opacity":1},
            "location":{
              "x":65,
              "y":150},
            "size":{
              "width":163,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"887004a9fcc54613bc53186f15a1f09a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC,
                  "opacity":1},
                "location":{
                  "x":65,
                  "y":150},
                "size":{
                  "width":163,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"68ce68f0ed374245867c9b61547298c0",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":22,
              "y":184},
            "size":{
              "width":446,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/注册/u12_line.png"}},
{
          "id":"81c0229349614b1d80bffa133bd92ac9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"10px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":22,
              "y":147},
            "size":{
              "width":28,
              "height":27},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "cornerRadiusTopLeft":"100"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50d35b1b6a744b1ab0511efb193f81b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"10px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":22,
                  "y":147},
                "size":{
                  "width":28,
                  "height":27},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "cornerRadiusTopLeft":"100"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u13.png"}},
{
          "id":"f025c568b5a641aeaa10ebb3768f0638",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC,
              "opacity":1},
            "location":{
              "x":23,
              "y":208},
            "size":{
              "width":109,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7352ccba1094d9e941b32df7eca35b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC,
                  "opacity":1},
                "location":{
                  "x":23,
                  "y":208},
                "size":{
                  "width":109,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"495b28edbf1149629723d2357d01546d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF949494},
            "location":{
              "x":14,
              "y":419},
            "size":{
              "width":440,
              "height":57}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce26d260e1514439893d995acbc0e1f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF949494},
                "location":{
                  "x":14,
                  "y":419},
                "size":{
                  "width":440,
                  "height":57}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/注册/u17.png"}},
{
          "id":"f8714969b285407e8f4ddf693c0bbcf2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "location":{
              "x":359,
              "y":196},
            "size":{
              "width":95,
              "height":44},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13b82183dce6451f860ba997df15a861",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "location":{
                  "x":359,
                  "y":196},
                "size":{
                  "width":95,
                  "height":44},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u19.png"}},
{
          "id":"03ec99427c29454ba23eed78388278f5",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":22,
              "y":241},
            "size":{
              "width":446,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/注册/u12_line.png"}},
{
          "id":"8db9afc21fe7428fac468ec9065f2fde",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC,
              "opacity":1},
            "location":{
              "x":22,
              "y":263},
            "size":{
              "width":91,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62d51614afe245bc81b171d74d5ae5b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC,
                  "opacity":1},
                "location":{
                  "x":22,
                  "y":263},
                "size":{
                  "width":91,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c3e83a6d5091411ea62f9df3c634ceca",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":23,
              "y":296},
            "size":{
              "width":446,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/注册/u12_line.png"}},
{
          "id":"a0ce827abeb94f4981e98c06ec59467b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC,
              "opacity":1},
            "location":{
              "x":23,
              "y":318},
            "size":{
              "width":181,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"069c07aa94544ba8b9c8e35f9b20ecca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC,
                  "opacity":1},
                "location":{
                  "x":23,
                  "y":318},
                "size":{
                  "width":181,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d0eb249ba7f242da91d5078af7cf9d5c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":25,
              "y":380},
            "size":{
              "width":18,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76c67cbbb35a41bb8a28d8528fd56b90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":25,
                  "y":380},
                "size":{
                  "width":18,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u27.png"}},
{
          "id":"550d0e5dac65472ab8cadd165fac9f27",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "location":{
              "x":65,
              "y":377},
            "size":{
              "width":276,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e3d2baed445245c3a921753f9e09c4b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "location":{
                  "x":65,
                  "y":377},
                "size":{
                  "width":276,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "9a06184d26c54ee582ad2ba8c660265f":{
      "scriptId":"u0"},
    "5d2488b846ba4cb09e901e32eece94de":{
      "scriptId":"u1"},
    "3de3bb8115224281b957f06cd9717bbb":{
      "scriptId":"u2"},
    "ca78d9e4984f4124952d04d573933b7a":{
      "scriptId":"u3"},
    "23e921cbe9714f358e52add9395e50b7":{
      "scriptId":"u4"},
    "438b75b1691c4d8f8f6119953b54dbe9":{
      "scriptId":"u5"},
    "5a39ed809c424d629545ff67f16aa634":{
      "scriptId":"u6"},
    "89632e324f4f46c7bd6d80eb22c2d59c":{
      "scriptId":"u7"},
    "f1efea38a6bd42e1a23790ecf521d90f":{
      "scriptId":"u8"},
    "42d4bf1697974e9da2ddefd23937e253":{
      "scriptId":"u9"},
    "3758d401c39d47699c588aa9171428a2":{
      "scriptId":"u10"},
    "887004a9fcc54613bc53186f15a1f09a":{
      "scriptId":"u11"},
    "68ce68f0ed374245867c9b61547298c0":{
      "scriptId":"u12"},
    "81c0229349614b1d80bffa133bd92ac9":{
      "scriptId":"u13"},
    "50d35b1b6a744b1ab0511efb193f81b3":{
      "scriptId":"u14"},
    "f025c568b5a641aeaa10ebb3768f0638":{
      "scriptId":"u15"},
    "e7352ccba1094d9e941b32df7eca35b5":{
      "scriptId":"u16"},
    "495b28edbf1149629723d2357d01546d":{
      "scriptId":"u17"},
    "ce26d260e1514439893d995acbc0e1f9":{
      "scriptId":"u18"},
    "f8714969b285407e8f4ddf693c0bbcf2":{
      "scriptId":"u19"},
    "13b82183dce6451f860ba997df15a861":{
      "scriptId":"u20"},
    "03ec99427c29454ba23eed78388278f5":{
      "scriptId":"u21"},
    "8db9afc21fe7428fac468ec9065f2fde":{
      "scriptId":"u22"},
    "62d51614afe245bc81b171d74d5ae5b4":{
      "scriptId":"u23"},
    "c3e83a6d5091411ea62f9df3c634ceca":{
      "scriptId":"u24"},
    "a0ce827abeb94f4981e98c06ec59467b":{
      "scriptId":"u25"},
    "069c07aa94544ba8b9c8e35f9b20ecca":{
      "scriptId":"u26"},
    "d0eb249ba7f242da91d5078af7cf9d5c":{
      "scriptId":"u27"},
    "76c67cbbb35a41bb8a28d8528fd56b90":{
      "scriptId":"u28"},
    "550d0e5dac65472ab8cadd165fac9f27":{
      "scriptId":"u29"},
    "e3d2baed445245c3a921753f9e09c4b3":{
      "scriptId":"u30"}}});